### ISSUE TITLE
Support Claude 3

### ISSUE THREAD

**Issue by AndreaOrru** [karthink/gptel#229]
API is now accessible. Claude 3 Opus is claimed to be the best performing model right now.

**Comment by karthink** [comment]
Done, please test.

**Comment by gregoryg** [comment]
@karthink this appears to work, although I'm having terrible issues with the Anthropic servers.  I got a good response on one of my tries using gptel, though - which is all that's needed for proof!

`(gptel-make-anthropic "Anthropic"
  :stream nil
  :key 'gptel-api-key)
`

The error I get on almost every request is a 529 Server Error, with a message of "Overloaded" which appears to be a usage problem on the Anthropic side according to https://docs.together.ai/docs/error-codes

**Comment by karthink** [comment]
Thanks. It would be good to test streaming responses as well.  It's working here but I'll wait for some confirmation before closing this issue.

BTW you probably want `:key gptel-api-key` instead of `:key 'gptel-api-key`.  I guard against the latter in the code but the former is the intended usage of `:key`.

**Comment by gregoryg** [comment]
Streaming works!  I have it off by default because my ordinary use is in Org Mode buffers with a custom markdown-to-org function.

I changed my `:key` slots to fit your suggestion - thank you!
