### ISSUE TITLE
Add override for prog/text mode

### ISSUE THREAD

**Issue by DanLipsitt** [karthink/gptel#287]
Yaml mode derives from text-mode, and so is detected as prose. It would be nice to have a customizable map to override whether certain modes are code or prose.

**Comment by karthink** [comment]
Thank you for the suggestion.  I consider the refactoring menu obsolete and will remove it in the next release, so this setting will be irrelevant.  Refactoring is already available from the main `gptel-menu`, I just need to make it more discoverable.

That said, I do intend to provide a way to create directives programmatically, so I will keep your suggestion in mind.

**Comment by DanLipsitt** [comment]
Thanks! Is "Respond in place" the refactoring feature you're talking about?

I do appreciate the way the refactor command attempts to adjust the prompt, so I look forward to seeing how that functionality evolves.

**Comment by karthink** [comment]
"Respond in place" is the equivalent of "Refactor in place", but all the other features are available too.  If you move point into a response and open the menu, you will see this:

![screenshot_20240419T230103](https://github.com/karthink/gptel/assets/8607532/86874de1-6928-4c00-9c18-cf1a05f3bcc0)

- Use `d Add directive` to add a refactoring directive (on top of a generic system message)
- Regenerate the response with `M-RET`
- Cycle through the original text (that was rewritten), and every past rewrite with `N` and `P`
- Ediff against any past version (or the original text) with `E`.  You can use a prefix arg (`C-u 2`) to ediff against the nth previous version.

The problem is that most users may not be aware of these features, since it requires moving point inside a response region and opening the menu.
