### ISSUE TITLE
Make `gptel-expert-commands` customizable

### ISSUE THREAD

**Issue by swflint** [karthink/gptel#288]
The variable `gptel-expert-commands` is described in #249, but is not discoverable (not described in `README.org` or shown in `M-x customize-group RET gptel`), but seems quite useful.  Would it make sense to make this a) customizable, and b) document it somewhere in README?

**Comment by karthink** [comment]
`gptel-expert-commands` is not documented because it was a temporary measure and not intended to be used except for troubleshooting issues.  I plan to deprecate it in favor of transient levels `(info "(transient) Enabling and Disabling Suffixes")`, which will require no additional settings in gptel.
