### ISSUE TITLE
Is it possible to interact with LLMs provided by an Open WebUI?

### ISSUE THREAD

**Issue by JonatanSahar** [karthink/gptel#306]
They are not stored locally as well, although I suspect that's not a problem. 
Open WebUI: https://github.com/open-webui/open-webui
Thanks for all you work!

**Comment by karthink** [comment]
I don't understand what this software does.  The installation instructions explain how to access Ollama, which gptel already does. Can you give me some more context?

**Comment by JonatanSahar** [comment]
As far as I understand it's a system for deploying models. In my case it's running on a remote server and I want to query that remote Ollama. I'm not sure how it handles HTTP requests..

**Comment by karthink** [comment]
Closing as there's no planned change on the gptel side.

If you have a specific suggestion please re-open.

**Comment by algal** [comment]
FYI, Open WebUI is an open source, self-hosted system for presenting an OpenAI-compatible API endpoint and also a web chat UI for accessing models, especially models which another inference server is actually running locally. My impression is that it has particularly good support for models served by Ollama, since I think it may come from the same team.

Since Open Web UI can expose models via an OpenAI-compatible API endpoint, yes, you can use gptel to access a model hosted by Open WebUI.

I just got this working myself. Here's a snippet that works if you are serving Open WebUI via http on the same machine as emacs:

```lisp
  (gptel-make-openai "OpenWebUI"         
    :host "localhost"
    :protocol "http:
    :key "KEY_FOR_ACCESSING_OPENWEBUI"
    :endpoint "/api/chat/completions"
    :stream t
    :models '("gemma3n:latest"))
```

And here is a snippet which works if you are serving OpenWebUI from a host called "box.local" with self-signed certs:

```emacs-lisp
  (gptel-make-openai "OpenWebUI"         
    :host "box.local"
    :curl-args '("--insecure") ; needed because I'm hosting with self-signed certs.
    :key "KEY_FOR_ACCESSING_OPENWEBUI"
    :endpoint "/api/chat/completions"
    :stream t
    :models '("gemma3n:latest"))
```

AFAICT, Open WebUI seems to be mature, widely used, fairly full featured, with support for multiple users, images, RAG, voice interface, etc... It might be the top open source system for self-hosting the chat interface?  (100k + GH stars; [reddit comment](https://www.reddit.com/r/selfhosted/comments/1jltdjq/comment/modpqgd/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button ) ). But I only started looking at these components 24 hours ago, so I welcome correction if wrong! 

@karthink, if you'd be interested in me adding a snippet like this to the gptel README for backend setups, let me know and I can create a PR.

**Comment by karthink** [comment]
@algal Yes, we need README sections for using gptel with OpenWebUI and liteLLM.  A PR is welcome!

**Comment by algal** [comment]
@karthink I raised a PR for this
