### ISSUE TITLE
Feature request: Option to default to a particular conversation buffer

### ISSUE THREAD

**Issue by jwiegley** [karthink/gptel#374]
Recently `gptel` has started asking me which buffer I want to use for my conversation with ChatGPT, every time that I invoke it. I tried defining a `my-gptel` command that calls `(gptel "*ChatGPT*")`, but this does not work. Apparently the code in the `interactive` form for `gptel` is doing more work than just selecting a buffer name.

So, my humble feature request is the ability to set a buffer name as a customization option, and have `M-x gptel` automatically choose that buffer if it has been set. Thank you!

**Comment by karthink** [comment]
@jwiegley First a solution, then an explanation.

**Solution 1**: Non-interactively, `gptel` just returns the buffer instead of displaying it.  So `my-gptel` can run
```elisp
(pop-to-buffer (gptel "*ChatGPT*"))
```
and it should work as expected.

**Solution 2**: `gptel` takes an optional `interactivep` argument, so in `my-gptel` you could have instead
```elisp
(gptel "*ChatGPT*" nil nil t)
```
but this is mostly used for internal plumbing purposes (when redirecting responses from the transient menu), so solution 1 is preferred to this.

In either case, you could do something like this if you use many chat buffers:
```elisp
;;; -*- lexical-binding: t; -*-
(defun gptel-cycle ()
  "Cycle through gptel buffers (with \"`\") in MRU fashion.

If no gptel buffers exist run `gptel'."
  (interactive)
  (if-let* ((bufs
            (match-buffers (lambda (b) (buffer-local-value 'gptel-mode b))))
           (next-buf
            (lambda () (interactive)
              (pop-to-buffer (gptel (car bufs)))
              (setq bufs (nconc (cdr bufs) (list (car bufs)))))))
      (progn
        (funcall next-buf)
        (set-transient-map (define-keymap "`" next-buf) t))
    (call-interactively #'gptel)))
```

Let me know if you still want the customization option (or a different solution perhaps.)

**Explanation**:

Sorry about the change!  I knew when making the change that the extra keystroke would annoy veteran Emacs users. But the plan was/is to reserve the prefix arg behavior (`C-u M-x gptel`) for a transient menu where you can specify the backend, system prompt and other parameters for a new gptel session, but I haven't implemented that yet.

**Comment by jwiegley** [comment]
Solution 1 works for me! I tried to write such a function, but was missing the `pop-to-buffer` wrapper around it. Thank you, and my continuing thanks for this great package! I use it very often.

**Comment by karthink** [comment]
> Thank you, and my continuing thanks for this great package! I use it very often.

My pleasure!  Out of curiosity, do you use any of gptel's features besides chat buffers? (redirecting prompts/responses, supplying context, refactoring etc)

**Comment by karthink** [comment]
Thanks John, that's interesting.  I tried to make it so gptel is available for queries from/to any buffer, but my impression is that most users either prefer to switch to the chat interface, or want project-aware, intelligent code completion (which gptel doesn't provide).
