### ISSUE TITLE
The model gpt-4 does not exist

### ISSUE THREAD

**Issue by drewverlee** [karthink/gptel#47]
Selecting gpt model gpt-4, and sending a prompt results in this message: ChatGPT error: (HTTP/2 404) The model: `gpt-4` does not exist.

Selecting gpt model gpt-3.5-turbo sends and receives an answer from the API.

If it's a configuration issue on my end I'm not sure what to do, i added this to my authstore (.authinfo): 

machine openai.com login apikey password <PASSWORD>

and i have a paid account on openai as well as for chatgpt+.

GPT-4 is a model in the open [ai docs.](https://platform.openai.com/docs/models/overview)

**Comment by karthink** [comment]
API access to GPT-4 is being rolled out slowly, see #43, #44, and the waitlist (https://openai.com/waitlist/gpt-4-api).

If you can successfully query GPT-4 from Curl or from another application through the API, this could be a bug with gptel, but based on the previous two threads I'd be surprised if the issue was gptel.

**Comment by karthink** [comment]
Closing now, please reopen if gptel doesn't work with gpt-4 after you get API access.
