### ISSUE TITLE
Custom chat prompt history with `gptel-request`

### ISSUE THREAD

**Issue by kadircancetin** [karthink/gptel#521]
**Describe the solution you'd like**

Currently, `gptel-request` can accept a prompt as a list of strings. However, it is not possible to provide multiple `assistant` or `user` messages consecutively, nor is it possible to start with an `assistant` message, which are capabilities available to LLMs.

I believe that accepting a prompt as `messages` (with a similar structure to `gptel-create-prompt`) would be a simple implementation and would enable more custom use cases.

Like:

```
((:role "user" :content "user text") (:role "assistant" :content "you give text") (:role "assistant" :content "you give empty response"))
```

**Comment by karthink** [comment]
> Currently, `gptel-request` can accept a prompt as a list of strings. However, it is not possible to provide multiple `assistant` or `user` messages consecutively, nor is it possible to start with an `assistant` message, which are capabilities available to LLMs.

This is not the case. You can provide any arrangement of user and assistant messages by setting the parts you don't want to `nil`:

``` emacs-lisp
("user text"                            ;user
 "you give text"                        ;assistant
 nil                                    ;user, filtered out
 "you give empty response")             ;assistant
```

See #520 for another example, where the user role is `nil`.

> I believe that accepting a prompt as `messages` (with a similar structure to `gptel-create-prompt`) would be a simple implementation and would enable more custom use cases.
> 
> Like:
> 
> ```
> ((:role "user" :content "user text") (:role "assistant" :content "you give text") (:role "assistant" :content "you give empty response"))
> ```
 
This appears to be everyone's first thought, and was mine too!  Every API has a different way of doing this, so adding one more gptel-specific method just causes more confusion.  Even within one API there are different ways of doing this -- for example Anthropic allows both

``` emacs-lisp
((:role "user" :content "user text")
 (:role "user" :content "more user text"))
```

and

``` emacs-lisp
((:role "user" :content [(:type "text" :text "user text")
                         (:type "text" :text "more user text")]))
```

The occasional extra `nil`s in the current method are a small price to pay for its simplicity and uniformity, especially considering the most common "happy path" is one where the messages alternate.

-----

Until recently gptel-request did allow for prompts to be a list of prompts actually produced by `gptel--create-prompt`, but I've removed this feature temporarily while fixing some stuff.  I'll add it back eventually, but there's no reason for users to avail themselves of this option since, as pointed out above, the shape of `gptel--create-prompt`'s output is highly variable depending on the backend, whether there are images in the prompt and other factors.  The recommended method is simple and uniform.

**Comment by kadircancetin** [comment]
> you can provide any arrangement of user and assistant messages by setting the parts you don't want to nil:

Oh, I didn't notice. This is cool, thank you :pray: Also thanks for all your works.

> Until recently gptel-request did allow for prompts to be a list of prompts actually 

I actually used it before and my last upgrade broke my integration. Because of I make very rare update, I didn't notice the changes. So, I had to use change gptel-request to `gptel-curl-get-response` https://github.com/kadircancetin/beyin/commit/189fabce21c8cb547ca03c95ddbcb19f7b108708 which is I think one of the worst think I could do :) . 

As far as I remember, passing `messages` was not documented feature, so I didn't want to open this ticket like it is a bug. 

Since we can give `nil` instead of string, I am very okay with this usage. We can close the issue, or keep it if we will add the support.

**Comment by karthink** [comment]
> my last upgrade of gptel broke my integration. Because of I make very rare update, I didn't notice the changes when it changed

Looking at https://github.com/kadircancetin/beyin/commit/189fabce21c8cb547ca03c95ddbcb19f7b108708#diff-0092be2f9e93e9275b8b7c9f5aea35c044d5e2cf3cb101f56333973f9fc4e40dL192, I don't see why `gptel-request` broke for you.

`gptel-request` has gained new features since it was first introduced but no existing feature was removed.  `gptel-request` is intended to be stable and backwards compatible.

**Comment by kadircancetin** [comment]
In this diff `(beyin--parse-buffer--for-gptel)` returns similar data type of `(gptel--create-prompt)` , which I give in first place

```
((:role "user" :content "user text") (:role "assistant" :content "you give text") (:role "assistant" :content "you give empty response"))
```

So I mean, at some point, I think this was working :point_right:  `(gptel-request (gptel--create-prompt))` but now it is not. Since it is not documented, I don't expect to support and open this issue.
