### ISSUE TITLE
Parallel conversations in split frames

### ISSUE THREAD

**Issue by jbarbero1** [karthink/gptel#523]
### Please update gptel first -- errors are often fixed by the time they're reported.

- [X] I have updated gptel to the latest commit and tested that the issue still exists

### Bug Description

When I split two gptel-mode frames and switch models in one of them, the model gets switched in the other conversation as well. This does not happen if only one buffer is visible at a time. This makes it hard to continue a chat with two LLMs side by side, since I keep having to switch models each time I want to send a message in the other frame.

An unrelated bug is that sometimes when sending to multiple LLMs at the same time, the contents of the responses will get mixed up. But this is something I can't easily reproduce, so I just wanted to mention it in case you might be aware of why it might be happening.

Thanks!

### Backend

None

### Steps to Reproduce

1. Open a vertical split frame
2. Enter gptel-mode in seprate buffers in each frame
3. Pick a model in one frame - the other frame's model will now change as well
4. Observe that this doesn't happen to non-visible buffers

### Additional Context

Emacs 29.4
macOS

**Comment by karthink** [comment]
> When I split two gptel-mode frames and switch models in one of them, the model gets switched in the other conversation as well.

This is by design.  The gptel model, backend and request parameters are global variables.  **To set them buffer-locally, flip the `=` switch in gptel's transient menu.**
 
> This does not happen if only one buffer is visible at a time.

Just tried, can't reproduce this.  As mentioned, gptel request parameters are global variables so they change in all buffers by default.

> An unrelated bug is that sometimes when sending to multiple LLMs at the same time, the contents of the responses will get mixed up. But this is something I can't easily reproduce, so I just wanted to mention it in case you might be aware of why it might be happening.

I wasn't aware of this.  Concurrent requests run in different process buffers with different process sentines, so I'm not sure how this is happening.  A reproducer will be helpful: basically you turn on logging with `(setq gptel-log-level 'debug)`, and when there's a mixup, capture the contents of the log and the chat buffers.

**Comment by jbarbero1** [comment]
Thanks, switching the setting to buffer-local worked. I think what happened is that when restoring a previous gptel-mode session, the setting somehow got lost. My apologies for the confusion!

**Comment by karthink** [comment]
> Thanks, switching the setting to buffer-local worked. I think what happened is that when restoring a previous gptel-mode session, the setting somehow got lost. My apologies for the confusion!

One thing to keep in mind is that if the model and other properties are saved as Org heading properties, those will always take priority.  So you have to save the buffer after changing the model to ensure that the saved properties are updated first.  (Or delete the properties block.)
